mbase_region_menu_style_orientation_footer: mb-menu-horizontal
mbase_region_menu_child_display_footer: mb-menu-dropup
mbase_region_menu_style_orientation_footer_social: mb-menu-horizontal
mbase_region_menu_child_display_footer_social: mb-menu-dropup
mbase_region_menu_style_orientation_footer_message: mb-menu-horizontal
mbase_region_menu_child_display_footer_message: mb-menu-dropup
