mbase_region_menu_style_orientation_footer_menu: mb-menu-horizontal
mbase_region_menu_child_display_footer_menu: mb-menu-dropno
mbase_region_menu_style_orientation_footer_social: mb-menu-horizontal
mbase_region_menu_child_display_footer_social: mb-menu-dropno
mbase_region_menu_style_orientation_footer_copyright: mb-menu-horizontal
mbase_region_menu_child_display_footer_copyright: mb-menu-dropno
