mbase_region_menu_style_orientation_footer: mb-menu-horizontal
mbase_region_menu_child_display_footer: mb-menu-dropno
mbase_region_menu_style_orientation_footer_menu1: mb-menu-vertical
mbase_region_menu_child_display_footer_menu1: mb-menu-dropno
mbase_region_menu_style_orientation_footer_menu2: mb-menu-vertical
mbase_region_menu_child_display_footer_menu2: mb-menu-dropno
mbase_region_menu_style_orientation_footer_menu3: mb-menu-vertical
mbase_region_menu_child_display_footer_menu3: mb-menu-dropno
mbase_region_menu_style_orientation_footer_social: mb-menu-vertical
mbase_region_menu_child_display_footer_social: mb-menu-dropno
mbase_region_menu_style_orientation_footer_copyright: mb-menu-horizontal
mbase_region_menu_child_display_footer_copyright: mb-menu-dropno
